### PR TITLE
Minor react-modal-wrapper fixes

### PR DESCRIPTION
**Pull request by PeteJodo**
Decided not switch out the portal dependencies since the one this is using has matured quite a bit and has a smaller footprint than the other potential module.

So I'm going to be closing: #10 and #13

### CODE REVIEW

**Comment by antialias** [comment]
What are portal dependencies?

**Comment by antialias** [comment]
oh, react-portal. Did it have a bunch of incompatible peer deps?

**Comment by PeteJodo** [comment]
They actually just removed peer deps and did some other stuff in order to support/prepare for React v0.15

**Comment by antialias** [comment]
Go ahead and publish

**Comment by PeteJodo** [comment]
there's no breaking changes so I'm going to make this a minor release

**Pull request merged**
