### PR TITLE
build is compatible with universal rendering

### PR DESCRIPTION
**Pull request by antialias**

### CODE REVIEW

**Comment by brettjashford** [comment]
pete's out for a couple weeks. gonna go ahead and merge this.

**Comment by antialias** [comment]
I don't have publish permission. do you @brettjashford ?

**Comment by antialias** [comment]
published 0.2.2 to local sinopia, but we need @PeteJodo to publish to the official npm repo ASAP.

**Comment by alejandromaka** [comment]
did you guys test this?
im not sure it will work without wrapping it in the withStyles helper

**Comment by alejandromaka** [comment]
as in itll compile but the styles wont load correctly

**Comment by antialias** [comment]
spoke off-git about this with @alejandromaka. No, the change was untested; I assumed `style-loader-isomorphic` was functionally identical to `style-loader`, but apparently it isn't.

**Comment by alejandromaka** [comment]
i opened this guy a few weeks ago https://github.com/1stdibs/react-modal-wrapper/pull/17 but i left it there until more testing was in place. unfortunately i never got to test it deeply, but seemed fine as far as i can tell

**Comment by antialias** [comment]
Seems that there is an app-side configuration necessary to get this working as well. I'm thinking that it would be best if the build used extracttext instead of style-loader, then the consuming app can use the exported stylesheet however it sees fit.

**Comment by brettjashford** [comment]
weird. i'm using dibs-com-modal which uses react-modal-wrapper@0.2.2
without any issues..

**Comment by alejandromaka** [comment]
i think the issue shows when trying to render the modal through server side. or at least thats what happened to me. so i think so far we dont have any projects that would make this issue appear.

**Comment by PeteJodo** [comment]
I'm replying from email since I don't get text messages and can't get by
two factor authentication for github. Do you really need me to publish. I
think the 1stdibs npm user has access to publishing. You can double check
on the npm website. Let me know if you really need me to publish, I can try
to find a way.

**Comment by antialias** [comment]
> Do you really need me to publish

@PeteJodo no! Please enjoy your vacation! Turns we can publish to our local registry without your account, so all should be well until you publish a later version to the public registry.

**Pull request merged**
