### PR TITLE
Use 1stdibs scoped react-portal

### PR DESCRIPTION
**Pull request by PeteJodo**

### CODE REVIEW

**Comment by PeteJodo** [comment]
@hellatan I don't think users of this package should have to worry about also installing `@1stdibs/react-portal`. Why did you remove it from dependencies again?

**Comment by hellatan** [comment]
can't remember. how big is react portal?

**Comment by PeteJodo** [comment]
I don't think that matters in this context? But it's 7.6K built

**Comment by hellatan** [comment]
if we have other packages loading react-portal, then we could have version issues, that's the main concern i probably had.

**Comment by PeteJodo** [comment]
I don't see that being an issue really. Nothing extra is built with react-portal and it's only purpose is for modals really

**Comment by hellatan** [comment]
dependency seems fine

**Comment by PeteJodo** [comment]
ok added as dep

**Comment by PeteJodo** [comment]
bump

**Comment by PeteJodo** [comment]
I'm going to bump this up to `v0.3.1` since it isn't a breaking change

**Comment by PeteJodo** [comment]
published `v0.3.1` sending out an email

**Pull request merged**
